//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.03 at 02:37:19 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.perscholas.com/xml/book", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.perscholas.xml.book;
